<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>FurniShop.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Database\Migrations\*.sql" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql" Version="8.0.5" />
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="PDFsharp" Version="6.1.1" />
    <PackageReference Include="ClosedXML" Version="0.104.1" />
    <PackageReference Include="ZXing.Net" Version="0.16.9" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FurniShop.Core\FurniShop.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="FurniShop.Tests" />
  </ItemGroup>
</Project>
